version: '3'
services:
  dynamodb:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    user: root
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    # environment:
    #   AWS_ACCESS_KEY_ID: 'FAKEID'
    #   AWS_SECRET_ACCESS_KEY: 'FAKEKEY'
    #   AWS_REGION: 'us-east-1'